export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_COLLECTION_FILTER:"REMOVE_COLLECTION_FILTER",
    ADD_COLLECTION_FILTER:"ADD_COLLECTION_FILTER",
    CLEAR_COLLECTION_FILTER:" CLEAR_COLLECTION_FILTER",
    // FILTER_COLLECTION_ARRAY:"FILTER_COLLECTION_ARRAY"
    CLEAR_DELETED_FILTER:"CLEAR_DELETED_FILTER",
    ADD_DELETED_FILTER:"ADD_DELETED_FILTER",
};